name: Test PA-API Install

on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create venv and install package
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install python-amazon-paapi

      - name: Verify import
        run: |
          source venv/bin/activate
          python -c "import python_amazon_paapi; print(python_amazon_paapi.__version__)"
