name: Update SSD Prices

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-prices:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'  # Caches dependencies for faster runs

      - name: Install python-amazon-paapi (Official Package)
        run: |
          python -m pip install --upgrade pip
          pip install python-amazon-paapi --no-cache-dir  # Force fresh install
          pip install requests  # Ensure dependency is present
          pip show python-amazon-paapi  # Verify installation

      - name: Run price fetcher
        env:
          AMAZON_ACCESS_KEY: ${{ secrets.AMAZON_ACCESS_KEY }}
          AMAZON_SECRET_KEY: ${{ secrets.AMAZON_SECRET_KEY }}
        run: |
          python -c "import python_amazon_paapi; print(f'Successfully imported {python_amazon_paapi.__version__}')"
          python fetcher.py

      - name: Commit changes
        if: success()
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated: Updated SSD prices"
          file_pattern: ssd_prices.json
