name: Update SSD Prices

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-prices:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          # Removed cache to avoid requirements.txt error

      - name: Install python-amazon-paapi
        run: |
          python -m pip install --upgrade pip
          pip install python-amazon-paapi requests
          pip freeze | grep amazon  # Verify installation

      - name: Debug Python environment
        run: |
          python -c "import sys; print(f'Python path: {sys.path}')"
          python -c "import python_amazon_paapi; print(f'Successfully imported version {python_amazon_paapi.__version__}')"

      - name: Run price fetcher
        env:
          AMAZON_ACCESS_KEY: ${{ secrets.AMAZON_ACCESS_KEY }}
          AMAZON_SECRET_KEY: ${{ secrets.AMAZON_SECRET_KEY }}
        run: python fetcher.py

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated: Updated SSD prices"
          file_pattern: ssd_prices.json
