name: Update SSD Prices

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # This step installs the required library. It must be correct.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install paapi

      # This step runs your Python script. It will now find the 'paapi' library.
      - name: Run Python script to fetch prices
        env:
          AMAZON_ACCESS_KEY: ${{ secrets.AMAZON_ACCESS_KEY }}
          AMAZON_SECRET_KEY: ${{ secrets.AMAZON_SECRET_KEY }}
        run: python fetcher.py

      # This step saves the results.
      - name: Commit and push if files changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated: Updated SSD prices"
          file_pattern: ssd_prices.json