name: Update SSD Prices

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:       # Manual trigger

jobs:
  update-prices:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set git credentials
        run: |
          git config --global url."https://x-access-token:${{  secrets.GITHUB_TOKEN }}@github.com".insteadOf "https://github.com" 

      - name: Install paapi5 SDK from GitHub
        run: |
          pip install git+https://github.com/Telefonica/amazon-paapi5-sdk.git 

      - name: Verify installation
        run: |
          pip list | grep -i paapi

      - name: Show Python path
        run: |
          python -c "import sys; print(sys.path)"

      - name: Fetch SSD prices via Amazon PA-API
        env:
          AMAZON_ACCESS_KEY: ${{ secrets.AMAZON_ACCESS_KEY }}
          AMAZON_SECRET_KEY: ${{ secrets.AMAZON_SECRET_KEY }}
          TAG_CA: strobify10-20
          TAG_UK: strobify10-20
          TAG_DE: strobify10-20
          TAG_FR: strobify10-20
          TAG_IT: strobify10-20
          TAG_ES: strobify10-20
          TAG_NL: strobify10-20
          TAG_PL: strobify10-20
          TAG_SE: strobify10-20
        run: |
          python fetcher.py
